version: '3.8'

services:

  backend:
    image: ghcr.io/educaware/camera-server:latest
    env_file:
      - .env
    ports:
      - "8080:8080"

  bot:
    image: ghcr.io/educaware/camera-bot:latest
    depends_on:
      - backend
    env_file:
      - .env
